"""Render a self-contained HTML viewer (ClaimGraph + commit-history timeline) from a payload.

Everything is inlined, so the output is a single file that works offline (``file://``) and embeds
anywhere: the viewer CSS/JS and Cytoscape are inlined from the bundled ``viewer/`` assets, and the
graph data rides in a ``<script type="application/json" id="cg-data">`` island the viewer reads
instead of fetching. Three shapes: ``page`` (standalone document), ``fragment`` (an isolated
``<iframe srcdoc>`` snippet to paste into another page), and ``branded`` (page + CKC chrome).
"""
from __future__ import annotations

import base64
import html
import json
from importlib import resources

SHAPES = ("page", "fragment", "branded")


def _text(name: str) -> str:
    return resources.files(__package__).joinpath("viewer", name).read_text(encoding="utf-8")


def _bytes(name: str) -> bytes:
    return resources.files(__package__).joinpath("viewer", name).read_bytes()


def _island(payload: dict) -> str:
    # Escape `</` so the JSON can never close the surrounding <script>; the viewer JSON.parses it.
    return json.dumps(payload, ensure_ascii=False).replace("</", "<\\/")


def _board(title: str, lede: str) -> str:
    return (
        '<header class="hero"><div class="wrap">\n'
        '  <div class="tag">Conventional Knowledge Commits</div>\n'
        f"  <h1>{html.escape(title)}</h1>\n"
        f'  <p class="lede">{lede}</p>\n'
        '  <div id="transport" class="transport" hidden role="group" aria-label="Replay the history">\n'
        '    <button id="tl-play" class="tl-btn" type="button" aria-pressed="false">&#9654; Play</button>\n'
        '    <button id="tl-prev" class="tl-btn" type="button" aria-label="Step back">&#8249;</button>\n'
        '    <input id="tl-range" class="tl-range" type="range" min="0" max="0" value="0" step="1" aria-label="Commit timeline">\n'
        '    <button id="tl-next" class="tl-btn" type="button" aria-label="Step forward">&#8250;</button>\n'
        '    <span id="tl-label" class="tl-label"></span>\n'
        "  </div>\n"
        "</div></header>\n"
        '<main class="board">\n'
        '  <div id="cy" aria-label="ClaimGraph visualization"></div>\n'
        '  <aside id="panel" class="panel">\n'
        '    <div class="legend">\n'
        '      <div class="tag">Effective status</div><ul class="swatches" id="status-legend"></ul>\n'
        '      <div class="tag">Relations</div><ul class="swatches" id="edge-legend"></ul>\n'
        "    </div>\n"
        '    <div id="detail" class="detail"><p class="hint">Select a claim to inspect its status and dependencies.</p></div>\n'
        "  </aside>\n"
        "</main>\n"
    )


def _nav() -> str:
    logo = base64.b64encode(_bytes("logo.png")).decode("ascii")
    return (
        '<nav class="nav"><div class="wrap">'
        '<a class="home" href="https://claimgraph.conventional-knowledge-commits.org/">'
        f'<img class="brand" src="data:image/png;base64,{logo}" alt="">ClaimGraph</a>'
        '<span class="sp"></span>'
        '<a class="ext" href="https://conventional-knowledge-commits.org/">Conventional Knowledge Commits ↗</a>'
        "</div></nav>\n"
    )


def _footer() -> str:
    return (
        '<footer><div class="wrap">Generated by '
        '<a href="https://github.com/hotherio/claimgraph">claimgraph</a> · part of '
        '<a href="https://conventional-knowledge-commits.org/">Conventional Knowledge Commits</a>.'
        "</div></footer>\n"
    )


def _document(title: str, body: str, payload: dict) -> str:
    return (
        '<!DOCTYPE html>\n<html lang="en">\n<head>\n'
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        '<link rel="icon" href="data:,">\n'  # self-contained: suppress the default favicon request
        f"<title>{html.escape(title)} · ClaimGraph</title>\n"
        "<style>\n" + _text("claimgraph.css") + "\n</style>\n"
        "</head>\n<body>\n"
        + body
        + '<script type="application/json" id="cg-data">' + _island(payload) + "</script>\n"
        + "<script>" + _text("cytoscape.min.js") + "</script>\n"
        + "<script>" + _text("claimgraph.js") + "</script>\n"
        + "</body>\n</html>\n"
    )


def render(payload: dict, shape: str = "page", title: str | None = None, lede: str | None = None) -> str:
    """Return a self-contained HTML string for the given ClaimGraph payload (with optional timeline)."""
    if shape not in SHAPES:
        raise ValueError(f"unknown shape {shape!r}; expected one of {SHAPES}")
    title = title or "ClaimGraph"
    lede = lede or (
        f"ClaimGraph and commit history for <b>{html.escape(title)}</b>. Node colour is the "
        "<b>effective status</b>; press <b>Play</b> to replay the commits, and click a claim to trace "
        "what it rests on."
    )
    body = _board(title, lede)
    if shape == "branded":
        body = _nav() + body + _footer()
    doc = _document(title, body, payload)
    if shape == "fragment":
        # Wrap the whole document in an iframe srcdoc: fully style/script-isolated from the host page,
        # still a single inline snippet to paste. The browser un-escapes srcdoc before parsing.
        srcdoc = html.escape(doc, quote=True)
        return (
            '<iframe class="claimgraph-embed" title="ClaimGraph" loading="lazy" '
            f'style="width:100%;height:680px;border:0" srcdoc="{srcdoc}"></iframe>\n'
        )
    return doc
